In [4]:
from glob import glob
import pandas as pd
glob("../data/interim/*_my_*transform*")

['../data/interim\\12_my_larva_transform.csv',
 '../data/interim\\17_my_creep_transform.csv',
 '../data/interim\\21_my_supply_transform.csv',
 '../data/interim\\25_my_economy_transform.csv',
 '../data/interim\\29_my_army_transform.csv',
 '../data/interim\\33_my_tech_transform.csv',
 '../data/interim\\4_my_larva_born_transform.csv',
 '../data/interim\\8_my_unspent_transform.csv']

In [5]:

glob("../data/interim/*_pro_*transform*")

['../data/interim\\12_pro_larva_transform.csv',
 '../data/interim\\17_pro_creep_transform.csv',
 '../data/interim\\21_pro_supply_transform.csv',
 '../data/interim\\25_pro_economy_transform.csv',
 '../data/interim\\29_pro_army_transform.csv',
 '../data/interim\\33_pro_tech_transform.csv',
 '../data/interim\\4_pro_larva_born_transform.csv',
 '../data/interim\\8_pro_unspent_transform.csv']

In [64]:
import matplotlib.pyplot as plt
from utils import *

#################
## Larva Borns ##
#################

pro_df = local.read.csv("4_pro_larva_born_transform", 'interim')
pro_terran_df = pro_df.query('opponent_race == "Terran"')


pro_zerg_df = pro_df.query('opponent_race == "Zerg"')


pro_protoss_df = pro_df.query('opponent_race == "Protoss"')


my_df = local.read.csv("4_my_larva_born_transform", 'interim')
my_df

my_df2 = local.read.csv("3_extract_my_larva_borns", "interim")
my_df2

player_wons = []
larva_borns_scores = []
game_numbers = []
matchups = []
for game_number in range(1, 333):
    temp_df = my_df[my_df['game_number'] == game_number].copy()
    temp_df2 = my_df2[my_df2['game_number'] == game_number].copy()
    if temp_df.shape[0] == 0:
        continue
        
    player_wons.append(1 if temp_df2.iloc[0].main_player_won == 'Win' else 0)
    matchup = temp_df2.iloc[0].opponent_race
    game_numbers.append(game_number)
    matchups.append(matchup)
    max_second = max(temp_df.second)
    if max_second < 420:
        larva_borns_scores.append(-1)
    else:
        my_score = float(temp_df.larva_born_count.sum())
        if matchup == "Terran":
            pro_score = sum(pro_terran_df[pro_terran_df['second'] <= max_second].groupby('second')['larva_born_count'].quantile(0.80))
        elif matchup == 'Zerg':
            pro_score = sum(pro_zerg_df[pro_zerg_df['second'] <= max_second].groupby('second')['larva_born_count'].quantile(0.80))
        else:
            pro_score = sum(pro_protoss_df[pro_protoss_df['second'] <= max_second].groupby('second')['larva_born_count'].quantile(0.80))
        if pro_score == 0:
            larva_borns_scores.append(1.0)
        else:
            larva_borns_scores.append(my_score/pro_score)

larva_borns_output_df = pd.DataFrame()
larva_borns_output_df['game_number'] = game_numbers
larva_borns_output_df['matchup'] = matchups
larva_borns_output_df['player_won'] = player_wons
larva_borns_output_df['larva_borns_score'] = larva_borns_scores
larva_borns_output_df

#############
## unspent ##
#############

pro_df = local.read.csv("8_pro_unspent_transform", 'interim')
pro_terran_df = pro_df.query('opponent_race == "Terran"')

pro_zerg_df = pro_df.query('opponent_race == "Zerg"')


pro_protoss_df = pro_df.query('opponent_race == "Protoss"')


my_df = local.read.csv("8_my_unspent_transform", 'interim')
my_df

my_df2 = local.read.csv("7_extract_my_unspent", "interim")
my_df2

# player_wons = []
unspent_scores = []
game_numbers = []
matchups = []
for game_number in range(1, 333):
    temp_df = my_df[my_df['game_number'] == game_number].copy()
    temp_df2 = my_df2[my_df2['game_number'] == game_number].copy()
    if temp_df.shape[0] == 0:
        continue
        
    # player_wons.append(1 if temp_df2.iloc[0].main_player_won == 'Win' else 0)
    matchup = temp_df2.iloc[0].opponent_race
    game_numbers.append(game_number)
    matchups.append(matchup)
    max_second = max(temp_df.second)
    if max_second < 420:
        unspent_scores.append(-1)
    else:
        my_score = float(temp_df.unspent_amount.sum())
        if matchup == "Terran":
            pro_score = sum(pro_terran_df[pro_terran_df['second'] <= max_second].groupby('second')['unspent_amount'].quantile(0.20))
        elif matchup == 'Zerg':
            pro_score = sum(pro_zerg_df[pro_zerg_df['second'] <= max_second].groupby('second')['unspent_amount'].quantile(0.20))
        else:
            pro_score = sum(pro_protoss_df[pro_protoss_df['second'] <= max_second].groupby('second')['unspent_amount'].quantile(0.20))
        if my_score == 0:
            unspent_scores.append(0.0)
        else:
            unspent_scores.append(pro_score/my_score)

unspent_output_df = pd.DataFrame()
unspent_output_df['game_number'] = game_numbers
unspent_output_df['matchup'] = matchups
# unspent_output_df['player_won'] = player_wons
unspent_output_df['unspent_score'] = unspent_scores
unspent_output_df

     game_number  matchup  unspent_score
0              1   Terran       0.540606
1              2     Zerg       0.384377
2              3   Terran       0.729041
3              4   Terran       0.730801
4              5   Terran       0.543496
..           ...      ...            ...
238          326  Protoss       0.546165
239          327   Terran       0.653925
240          328     Zerg       0.561464
241          330     Zerg       0.456881
242          331     Zerg       0.475142

[243 rows x 3 columns]

In [72]:
#############
## larva ##
#############

pro_df = local.read.csv("12_pro_larva_transform", 'interim')
pro_terran_df = pro_df.query('opponent_race == "Terran"')

pro_zerg_df = pro_df.query('opponent_race == "Zerg"')


pro_protoss_df = pro_df.query('opponent_race == "Protoss"')


my_df = local.read.csv("12_my_larva_transform", 'interim')
my_df

my_df2 = local.read.csv("11_extract_my_larva", "interim")
my_df2

# player_wons = []
larva_scores = []
game_numbers = []
matchups = []
for game_number in range(1, 333):
    temp_df = my_df[my_df['game_number'] == game_number].copy()
    temp_df2 = my_df2[my_df2['game_number'] == game_number].copy()
    if temp_df.shape[0] == 0:
        continue
        
    # player_wons.append(1 if temp_df2.iloc[0].main_player_won == 'Win' else 0)
    matchup = temp_df2.iloc[0].opponent_race
    game_numbers.append(game_number)
    matchups.append(matchup)
    max_second = max(temp_df.second)
    if max_second < 420:
        larva_scores.append(-1)
    else:
        my_score = float(temp_df.larva_amount.sum())
        if matchup == "Terran":
            pro_score = sum(pro_terran_df[pro_terran_df['second'] <= max_second].groupby('second')['larva_amount'].quantile(0.20))
        elif matchup == 'Zerg':
            pro_score = sum(pro_zerg_df[pro_zerg_df['second'] <= max_second].groupby('second')['larva_amount'].quantile(0.20))
        else:
            pro_score = sum(pro_protoss_df[pro_protoss_df['second'] <= max_second].groupby('second')['larva_amount'].quantile(0.20))
        if my_score == 0:
            larva_scores.append(0.0)
        else:
            larva_scores.append(pro_score/my_score)

larva_output_df = pd.DataFrame()
larva_output_df['game_number'] = game_numbers
larva_output_df['matchup'] = matchups
# larva_output_df['player_won'] = player_wons
larva_output_df['larva_score'] = larva_scores
larva_output_df

     game_number  matchup  larva_score
0              1   Terran     0.800967
1              2     Zerg     0.529732
2              3   Terran     0.847003
3              4   Terran     0.597432
4              5   Terran     0.755232
..           ...      ...          ...
237          325  Protoss     0.750202
238          326   Terran     0.602468
239          327     Zerg     0.568172
240          329     Zerg     0.903015
241          330     Zerg     0.491851

[242 rows x 3 columns]

In [68]:
#############
## creep ##
#############

pro_df = local.read.csv("17_pro_creep_transform", 'interim')
pro_terran_df = pro_df.query('opponent_race == "Terran"')

pro_zerg_df = pro_df.query('opponent_race == "Zerg"')


pro_protoss_df = pro_df.query('opponent_race == "Protoss"')


my_df = local.read.csv("17_my_creep_transform", 'interim')
my_df

my_df2 = local.read.csv("16_extract_my_creeps", "interim")
my_df2

# player_wons = []
creep_scores = []
game_numbers = []
matchups = []
for game_number in range(1, 333):
    temp_df = my_df[my_df['game_number'] == game_number].copy()
    temp_df2 = my_df2[my_df2['game_number'] == game_number].copy()
    if temp_df.shape[0] == 0:
        continue
        
    # player_wons.append(1 if temp_df2.iloc[0].main_player_won == 'Win' else 0)
    matchup = temp_df2.iloc[0].opponent_race
    game_numbers.append(game_number)
    matchups.append(matchup)
    max_second = max(temp_df.second)
    if max_second < 420:
        creep_scores.append(-1)
    else:
        my_score = float(temp_df.creep_count.sum())
        if matchup == "Terran":
            pro_score = sum(pro_terran_df[pro_terran_df['second'] <= max_second].groupby('second')['creep_count'].quantile(0.80))
        elif matchup == 'Zerg':
            pro_score = sum(pro_zerg_df[pro_zerg_df['second'] <= max_second].groupby('second')['creep_count'].quantile(0.80))
        else:
            pro_score = sum(pro_protoss_df[pro_protoss_df['second'] <= max_second].groupby('second')['creep_count'].quantile(0.80))
        if pro_score == 0:
            creep_scores.append(1.0)
        else:
            creep_scores.append(my_score/pro_score)

creep_output_df = pd.DataFrame()
creep_output_df['game_number'] = game_numbers
creep_output_df['matchup'] = matchups
# creep_output_df['player_won'] = player_wons
creep_output_df['creep_score'] = creep_scores
creep_output_df

     game_number  matchup  creep_score
0              1   Terran     1.191355
1              2     Zerg    11.181041
2              3   Terran     0.664160
3              4   Terran     1.734889
4              5   Terran     1.257121
..           ...      ...          ...
212          325     Zerg    26.858513
213          326  Protoss     0.594284
214          327   Terran     0.825009
215          328     Zerg    28.786458
216          331     Zerg    14.125964

[217 rows x 3 columns]

In [78]:
#############
## supply ##
#############

pro_df = local.read.csv("21_pro_supply_transform", 'interim')
pro_terran_df = pro_df.query('opponent_race == "Terran"')

pro_zerg_df = pro_df.query('opponent_race == "Zerg"')


pro_protoss_df = pro_df.query('opponent_race == "Protoss"')


my_df = local.read.csv("21_my_supply_transform", 'interim')
my_df

my_df2 = local.read.csv("20_extract_my_supply", "interim")
my_df2

# player_wons = []
supply_scores = []
game_numbers = []
matchups = []
for game_number in range(1, 333):
    temp_df = my_df[my_df['game_number'] == game_number].copy()
    temp_df2 = my_df2[my_df2['game_number'] == game_number].copy()
    if temp_df.shape[0] == 0:
        continue
        
    # player_wons.append(1 if temp_df2.iloc[0].main_player_won == 'Win' else 0)
    matchup = temp_df2.iloc[0].opponent_race
    game_numbers.append(game_number)
    matchups.append(matchup)
    max_second = max(temp_df.second)
    if max_second < 420:
        supply_scores.append(-1)
    else:
        my_score = float(temp_df.supply_amount.sum())
        if matchup == "Terran":
            pro_score = sum(pro_terran_df[pro_terran_df['second'] <= max_second].groupby('second')['supply_amount'].quantile(0.80))
        elif matchup == 'Zerg':
            pro_score = sum(pro_zerg_df[pro_zerg_df['second'] <= max_second].groupby('second')['supply_amount'].quantile(0.80))
        else:
            pro_score = sum(pro_protoss_df[pro_protoss_df['second'] <= max_second].groupby('second')['supply_amount'].quantile(0.80))
        if pro_score == 0:
            supply_scores.append(1.0)
        else:
            supply_scores.append(my_score/pro_score)

supply_output_df = pd.DataFrame()
supply_output_df['game_number'] = game_numbers
supply_output_df['matchup'] = matchups
# supply_output_df['player_won'] = player_wons
supply_output_df['supply_score'] = supply_scores
supply_output_df

     game_number  matchup  supply_score
0              1   Terran      0.885100
1              2     Zerg      0.888218
2              3   Terran      0.757532
3              4   Terran      1.040079
4              5   Terran      0.893540
..           ...      ...           ...
238          326  Protoss      0.929776
239          327   Terran      0.951416
240          328     Zerg      0.945453
241          330     Zerg      0.928430
242          331     Zerg      0.899582

[243 rows x 3 columns]